export const ApiError = {
  EMAIL_REGISTERED: 'EMAIL_REGISTERED',
  INVALID_AUTH_TOKEN: 'INVALID_AUTH_TOKEN',
  EXPIRED_AUTH_TOKEN: 'EXPIRED_AUTH_TOKEN',
  INVALID_LOGIN_CODE: 'INVALID_LOGIN_CODE',
  EXPIRED_LOGIN_CODE: 'EXPIRED_LOGIN_CODE',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  UNABLE_TO_SEND: 'UNABLE_TO_SEND',
  MODULE_NOT_FOUND: 'MODULE_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ITEM_NOT_FOUND: 'ITEM_NOT_FOUND',
  REQUEST_VALIDATION_FAILED: 'REQUEST_VALIDATION_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  DATA_ALREADY_EXISTS: 'DATA_ALREADY_EXISTS',
  UNKNOWN_OPERATION: 'UNKNOWN_OPERATION',
  FORBIDDEN_OPERATION: 'FORBIDDEN_OPERATION',
  CONFLICT: 'CONFLICT',
} as const;

export type ApiError = (typeof ApiError)[keyof typeof ApiError];

export const ValidationError = {
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_LOGIN_CODE: 'INVALID_LOGIN_CODE',
  STRING_REQUIRED: 'STRING_REQUIRED',
  NUMBER_REQUIRED: 'NUMBER_REQUIRED',
  ARRAY_REQUIRED: 'ARRAY_REQUIRED',
  OBJECT_REQUIRED: 'OBJECT_REQUIRED',
  BOOLEAN_REQUIRED: 'BOOLEAN_REQUIRED',
  NULLABLE_FIELD_REQUIRED: 'NULLABLE_FIELD_REQUIRED',
  MIN_LENGTH: 'MIN_LENGTH',
  MAX_LENGTH: 'MAX_LENGTH',
  EXACT_LENGTH: 'EXACT_LENGTH',
  MIN_VALUE: 'MIN_VALUE',
  MAX_VALUE: 'MAX_VALUE',
  MAX_ITEM_COUNT: 'MAX_ITEM_COUNT',
  INVALID_FORMAT: 'INVALID_FORMAT',
  INVALID_DATE: 'INVALID_DATE',
  INVALID_TIME: 'INVALID_TIME',
  INVALID_URL: 'INVALID_URL',
  INVALID_UUID: 'INVALID_UUID',
  NOT_SUPPORTED_VALUE: 'NOT_SUPPORTED_VALUE',
  DECK_CARD_LANGUAGE_MISMATCH: 'DECK_CARD_LANGUAGE_MISMATCH',
  LANGUAGE_MUST_NOT_CHANGE: 'LANGUAGE_MUST_NOT_CHANGE',
} as const;

export type ValidationError = (typeof ValidationError)[keyof typeof ValidationError];
