services:
  fw-mongodb_server:
    image: mongo:8.0
    environment:
      MONGO_INITDB_DATABASE: frazewise
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 28017:27017
    volumes:
      - ./dev-db.mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - fw-mongodb_data_container:/data/db

volumes:
  fw-mongodb_data_container:
