import {
  tablerAlertTriangle,
  tablerArrowsMaximize,
  tablerCheck,
  tablerChevronDown,
  tablerChevronLeft,
  tablerChevronRight,
  tablerChevronUp,
  tablerCloudDown,
  tablerCloudDownload,
  tablerDots,
  tablerEdit,
  tablerHash,
  tablerLanguage,
  tablerLogout,
  tablerPlus,
  tablerTextPlus,
  tablerTrash,
  tablerVolume,
  tablerX,
} from '@ng-icons/tabler-icons';

export const icons = {
  tablerAlertTriangle,
  tablerArrowsMaximize,
  tablerCheck,
  tablerChevronDown,
  tablerChevronLeft,
  tablerChevronRight,
  tablerChevronUp,
  tablerCloudDown,
  tablerCloudDownload,
  tablerDots,
  tablerEdit,
  tablerHash,
  tablerLanguage,
  tablerLogout,
  tablerPlus,
  tablerTextPlus,
  tablerTrash,
  tablerVolume,
  tablerX,
};
