import {
  tablerAlertTriangle,
  tablerArrowsMaximize,
  tablerCheck,
  tablerChevronDown,
  tablerChevronLeft,
  tablerChevronRight,
  tablerChevronUp,
  tablerCloudDown,
  tablerCloudDownload,
  tablerDeviceFloppy,
  tablerDots,
  tablerEdit,
  tablerFileExport,
  tablerFileImport,
  tablerFileUpload,
  tablerHash,
  tablerHome,
  tablerInfoCircle,
  tablerLanguage,
  tablerLogout,
  tablerMenu2,
  tablerMoon,
  tablerPlus,
  tablerSettings,
  tablerSparkles,
  tablerSunHigh,
  tablerTextPlus,
  tablerTrash,
  tablerVersions,
  tablerVolume,
  tablerX,
} from '@ng-icons/tabler-icons';

/**
 * Icons:
 * https://ng-icons.github.io/ng-icons/#/browse-icons
 * --> Choose Tabler icons --> scroll down
 */
export const icons = {
  tablerAlertTriangle,
  tablerArrowsMaximize,
  tablerCheck,
  tablerChevronDown,
  tablerChevronLeft,
  tablerChevronRight,
  tablerChevronUp,
  tablerCloudDown,
  tablerCloudDownload,
  tablerDeviceFloppy,
  tablerDots,
  tablerEdit,
  tablerFileExport,
  tablerFileImport,
  tablerFileUpload,
  tablerHash,
  tablerHome,
  tablerInfoCircle,
  tablerLanguage,
  tablerLogout,
  tablerMenu2,
  tablerMoon,
  tablerPlus,
  tablerSettings,
  tablerSparkles,
  tablerSunHigh,
  tablerTextPlus,
  tablerTrash,
  tablerVersions,
  tablerVolume,
  tablerX,
};
