name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  ci:
    name: FrazeWise CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.5.1'

      - name: Install dependencies
        run: npm ci

      - name: Run the linter
        run: npm run lint

      - name: Run format check
        run: npm run format:check

      - name: Run API build
        run: npm run build:check:api

      - name: Run UI build
        run: npm run build:ui
